name: Deploy to EC2
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws configure set default.region us-east-1
      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP}}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt-get install libpq-dev python3-dev -y
            cd /home/ubuntu/wordbot-discord
            git pull origin main
            sudo cp wordchain.service /etc/systemd/system/wordchain.service
            sudo cp web.service /etc/systemd/system/web.service
            mkdir -p logs
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl enable wordchain.service
            sudo systemctl enable web.service
            sudo systemctl restart wordchain.service
            sudo systemctl restart web.service
            sudo systemctl restart nginx.service
